/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef LOCALGEN-MAPCREATER_PRIVATE_H
#define LOCALGEN-MAPCREATER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.2.16"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	2
#define VER_BUILD	16
#define COMPANY_NAME	""
#define FILE_VERSION	"0.1.2.16"
#define FILE_DESCRIPTION	"The Official LocalGen Map Generator"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"AppOfficer (c) 2022 All rights reserved."
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.1.2.16"

#endif /*LOCALGEN-MAPCREATER_PRIVATE_H*/
